[tool.poetry]
name = "yapapi"
version = "0.1.0"
description = "Hi-Level API for Golem The Next Milestone"
authors = ["Przemysław K. Rekucki <przemyslaw.rekucki@golem.network>"]
license = "LGPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.6.1"
aiohttp = "^3.6.2"
dataclasses = { version = "^0.7", python = ">=3.6, <3.7"}
ya-market = {git = "https://github.com/prekucki/ya-client-python-market.git"}
urllib3 = "^1.25.9"

[tool.poetry.dev-dependencies]
setuptools = "black"
black = "^19.10b0"
pytest = "^5.4.3"
pre-commit = "^2.5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
