name: Continuous integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  pytest:
    name: PyTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: Gr1N/setup-poetry@v2
      with:
        poetry-version: 1.0.0
    - run: poetry install
    - run: poetry run pytest

